# Generated by Django 6.0 on 2025-12-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaccion',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.RenameField(
            model_name='reaccion',
            old_name='fecha_creacion',
            new_name='fecha_publicacion',
        ),
    ]
