# Generated by Django 6.0 on 2025-12-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_reaccion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='¿Aprobado?'),
        ),
    ]
