# Generated by Django 6.0 on 2025-12-16 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comentario_aprobado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('moderar_comentarios', 'Puede moderar comentarios de otros usuarios'), ('ver_comentarios_pendientes', 'Puede ver comentarios pendientes')]},
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='aprobado',
        ),
        migrations.AddField(
            model_name='comentario',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de aprobación'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_moderacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de moderación'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='moderado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_moderados', to=settings.AUTH_USER_MODEL, verbose_name='Moderado por'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo (si aplica)'),
        ),
    ]
