# Generated by Django 6.0 on 2025-12-15 05:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creador de la categoría'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen_destacada',
            field=models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categorias/', verbose_name='Imagen destacada'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.IntegerField(default=0, help_text='Número para ordenar las categorías (menor = primero)', verbose_name='Orden de visualización'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='titulo_viaje',
            field=models.CharField(blank=True, help_text="Ej: 'Aventura en la Patagonia Argentina'", max_length=200, null=True, verbose_name='Título del viaje de ejemplo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.categoria'),
        ),
    ]
