# Generated by Django 6.0 on 2025-12-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_categoria_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AddField(
            model_name='post',
            name='dificultad',
            field=models.CharField(blank=True, choices=[('facil', 'Fácil'), ('moderado', 'Moderado'), ('dificil', 'Difícil')], max_length=20, verbose_name='Dificultad'),
        ),
        migrations.AddField(
            model_name='post',
            name='mejor_epoca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mejor época para visitar'),
        ),
        migrations.AddField(
            model_name='post',
            name='precio_aproximado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Precio aproximado'),
        ),
        migrations.AddField(
            model_name='post',
            name='ubicacion_ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad/Región'),
        ),
        migrations.AddField(
            model_name='post',
            name='ubicacion_pais',
            field=models.CharField(blank=True, max_length=100, verbose_name='País'),
        ),
    ]
