# Generated by Django 6.0 on 2025-12-16 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_estado_post_resumen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_publicacion'], 'permissions': [('can_publish', 'Puede publicar posts'), ('can_review', 'Puede revisar posts')], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='publicado',
        ),
        migrations.AddField(
            model_name='post',
            name='duracia_recomendada',
            field=models.CharField(blank=True, max_length=50, verbose_name='Duración recomendada'),
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='post',
            name='palabras_clave',
            field=models.CharField(blank=True, max_length=200, verbose_name='Palabras clave'),
        ),
        migrations.AddField(
            model_name='post',
            name='visibilidad',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('solo_colaboradores', 'Solo colaboradores')], default='publico', max_length=20, verbose_name='Visibilidad'),
        ),
        migrations.AddField(
            model_name='post',
            name='vistas',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de vistas'),
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.categoria', verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(verbose_name='Contenido completo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dificultad',
            field=models.CharField(blank=True, choices=[('facil', 'Fácil'), ('moderado', 'Moderado'), ('dificil', 'Difícil'), ('muy_dificil', 'Muy difícil')], max_length=20, verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='post',
            name='resumen',
            field=models.TextField(help_text='Máximo 300 caracteres. Aparece en las vistas previas.', max_length=300, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
