# Generated by Django 6.0 on 2025-12-16 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Color en formato hexadecimal (ej: #6c757d)', max_length=7),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, help_text='Nombre de icono de Bootstrap Icons (ej: bi-globe)', max_length=50),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categorias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
