# Generated by Django 6.0 on 2025-12-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options_post_dificultad_post_mejor_epoca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='post',
            name='resumen',
            field=models.TextField(blank=True, help_text='Breve descripción que aparece en listas (máx. 200 caracteres)', max_length=200, verbose_name='Resumen'),
        ),
    ]
