# Generated by Django 6.0 on 2025-12-16 04:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_options_remove_post_publicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cache_version',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='last_cache_invalidation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
