# Generated by Django 6.0 on 2025-12-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default='2000-01-01', null=True, verbose_name='Fecha Nacimiento'),
        ),
    ]
